<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625200325 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE readers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, borrower_card_number VARCHAR(6) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE books ADD reader_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE books DROP is_borrowed');
        $this->addSql('ALTER TABLE books DROP borrower_card_number');
        $this->addSql('ALTER TABLE books ADD CONSTRAINT FK_4A1B2A921717D737 FOREIGN KEY (reader_id) REFERENCES readers (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_4A1B2A921717D737 ON books (reader_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE readers');
        $this->addSql('ALTER TABLE books DROP CONSTRAINT FK_4A1B2A921717D737');
        $this->addSql('DROP INDEX IDX_4A1B2A921717D737');
        $this->addSql('ALTER TABLE books ADD is_borrowed BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE books ADD borrower_card_number VARCHAR(6) DEFAULT NULL');
        $this->addSql('ALTER TABLE books DROP reader_id');
    }
}
